<?php


// if (!function_exists("sendNotification")) { 

//     function sendNotification($to, $data)    
//     {

       
//         $api_key = "AAAAP9vgqPY:APA91bFbvBFy7kCQurojUIcYADms8g0uUvSNxF9T8IPhes9XjKjDUbV-ZnWjg6Qc8IEnjKOYqTITzRvQZPdJYvn42kpCNHWIQPisLd1IHkCIAsX12KJZ-aHgd0Gj_jCYzUn4VFX1SWLK";
//         $url = "https://fcm.googleapis.com/fcm/send";
//         $fields = json_encode(array('to' => $to, 'notification' => $data));
//         // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//         $ch = curl_init();

//         curl_setopt($ch, CURLOPT_URL, $url);
//         curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
//         curl_setopt($ch, CURLOPT_POST, 1);
//         curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

//         $headers = array();
//         $headers[] = 'Authorization: key =' . $api_key;
//         $headers[] = 'Content-Type: application/json';
//         curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

//         $result = curl_exec($ch);
//         if (curl_errno($ch)) {
//             echo 'Error:' . curl_error($ch);
//         }
//         curl_close($ch);
//         return $result;
//     }
// } 

?>